# Generated by Django 2.0.1 on 2018-01-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='If',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=100)),
                ('iff', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
