# Generated by Django 2.0.1 on 2018-01-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifsearch', '0002_auto_20180125_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='if',
            name='iff',
            field=models.FloatField(),
        ),
    ]
